version: "2"
run:
  timeout: 5m
  tests: true

linters:
  enable:
    - staticcheck
    - ineffassign
    - govet
    - errcheck
  disable:
    - godot

linters-settings:
  errcheck:
    ignore:
      - ".*Encode"
      - ".*Write"
      - ".*Execute"

