version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - staticcheck
    - errcheck
    - ineffassign
  disable:
    - godot

linters-settings:
  errcheck:
    exclude:
      - "json.Encoder.Encode"
      - "tmpl.Execute"
      - "rows.Close"