version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - staticcheck
    - errcheck
    - ineffassign
    - gofumpt
    - gosimple
  disable:
    - godot

linters-settings:
  gofumpt:
    extra-rules: true