version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - staticcheck
    - ineffassign
    - govet
    - errcheck
  disable:
    - godot
  settings:
    errcheck:
      exclude-functions:
        - "fmt.Fprintf"
        - "fmt.Fprintln"
        - "(*bytes.Buffer).Write"
        - "(*bytes.Buffer).WriteString"