FROM golang:latest AS builder
WORKDIR /whoknows
RUN go install github.com/cosmtrek/air@latest
ENV PATH="/root/go/bin:${PATH}"
COPY go.mod go.sum ./
RUN go mod download
COPY go/. .
EXPOSE 8080
CMD ["go", "run", "main.go"]