FROM golang:1.25.3 AS builder
WORKDIR /whoknows/go
COPY go/go.mod go/go.sum ./
RUN go mod download
COPY go/ ./
RUN CGO_ENABLED=0 go build -ldflags="-s -w" -o app .

FROM debian:bookworm-slim
WORKDIR /whoknows/go
COPY --from=builder /whoknows/go/app .
RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates=20230311+deb12u1 \
    && update-ca-certificates \
    && rm -rf /var/lib/apt/lists/*
EXPOSE 8080
CMD ["./app"]