FROM golang:1.25.3 AS builder
WORKDIR /whoknows

COPY go/go.mod go/go.sum ./
RUN go mod download

RUN go install github.com/air-verse/air@v1.63.0
ENV PATH="/root/go/bin:${PATH}"

COPY go/. .

EXPOSE 8080
CMD ["go", "run", "main.go"]