FROM golang:1.25.3 AS builder
WORKDIR /whoknows/go
COPY go/go.mod go/go.sum ./
RUN go mod download
COPY go/ ./
RUN go build -o app .

FROM debian:bookworm-slim
WORKDIR /whoknows/go
COPY --from=builder /whoknows/go/app .
EXPOSE 8080
CMD ["./app"]