FROM golang:1.25.3 AS builder
WORKDIR /whoknows
RUN go install github.com/air-verse/air@1.63.0
ENV PATH="/root/go/bin:${PATH}"
COPY go/go.mod go/go.sum ./
RUN go mod download
COPY go/. .
EXPOSE 8080
CMD ["go", "run", "main.go"]