FROM golang:latest AS builder

WORKDIR /whoknows

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o whoknows main.go

FROM debian:bookworm-slim

WORKDIR /whoknows

COPY --from=builder /whoknows /whoknows

EXPOSE 8080

CMD ["./whoknows"]