name: Deploy to Azure VM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.AZURE_USERNAME }}
          key: ${{ secrets.AZURE_KEY }}
          port: 22
          script: |
            # Check Go version (should already be installed on Ubuntu VM)
            go version
            which go
            
            # Handle repository - simplified approach
            if [ -d ~/whoknows/.git ]; then
                echo "Repository exists, updating..."
                cd ~/whoknows
                git reset --hard
                git pull origin main
            else
                echo "Cloning repository..."
                rm -rf ~/whoknows
                git clone https://github.com/DVK-DEVOPS/DVK-Project.git ~/whoknows
            fi
            
            # Build the application
            cd ~/whoknows/go
            echo "Building application..."
            go build -o ~/whoknows/app .

            # Stop any running instance
            pkill -f 'whoknows/app' || true
            sleep 2  # Give processes time to stop

            # Start the app in background
            cd ~/whoknows
            nohup ./app > app.log 2>&1 &
            
            echo "Deployment completed!"
            echo "App PID: $!"