name: Deploy to Azure VM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    timeout-minutes: 1
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.AZURE_USERNAME }}
          key: ${{ secrets.AZURE_KEY }}
          port: 22
          script: |
           # Install Go 1.25
            wget https://go.dev/dl/go1.25.2.linux-amd64.tar.gz
            sudo rm -rf /usr/local/go
            sudo tar -C /usr/local -xzf go1.25.2.linux-amd64.tar.gz
            echo "export PATH=\$PATH:/usr/local/go/bin" >> ~/.profile
            source ~/.profile
            go version
            
            # Go to app folder or clone if missing
            cd ~/whoknows
            if [ -d .git ]; then
                  git reset --hard
                  git pull origin main
            else
                  rm -rf ~/whoknows/*
                  git init
                  git remote add origin https://github.com/DVK-DEVOPS/DVK-Project.git
                  git fetch origin
                  git checkout -t origin/main
            fi
            cd ~/whoknows/go
            go build -o ~/whoknows/app .

            # Stop any running instance
            pkill -f '~/whoknows/app' || true

            # Start the app in background
            setsid ~/whoknows/app > ~/whoknows/app.log 2>&1 < /dev/null &
            
            echo "Deployment completed!"
