name: Deploy to Azure VM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.AZURE_USERNAME }}
          key: ${{ secrets.AZURE_KEY }}
          port: 22
          script: |
            # Handle repository - simplified approach
            if [ -d ~/whoknows/.git ]; then
                echo "Repository exists, updating..."
                cd ~/whoknows
                git reset --hard
                git pull origin main
            else
                echo "Cloning repository..."
                rm -rf ~/whoknows
                git clone https://github.com/DVK-DEVOPS/DVK-Project.git ~/whoknows
            fi
            
            # Build the application
            cd ~/whoknows/go
            go build -o ~/whoknows/app .

            # Create systemd service for better process management
            sudo tee /etc/systemd/system/whoknows.service > /dev/null <<EOF
  [Unit]
  Description=WhoKnows Application
  After=network.target
  
  [Service]
  Type=simple
  User=$(whoami)
  WorkingDirectory=$HOME/whoknows
  ExecStart=$HOME/whoknows/app
  Restart=always
  RestartSec=5
  StandardOutput=append:$HOME/whoknows/app.log
  StandardError=append:$HOME/whoknows/app.log
  
  [Install]
  WantedBy=multi-user.target
  EOF
  
  sudo systemctl daemon-reload
  sudo systemctl stop whoknows || true
  sudo systemctl enable whoknows
  sudo systemctl start whoknows
  
  echo "Deployment completed!"