name: Continuous Delivery

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DOCKER_GITHUB_USERNAME: ${{ github.actor }}

permissions:
    contents: read
    packages: write
    attestations: write
    id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ env.DOCKER_GITHUB_USERNAME }}
          password: ${{ env.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
            docker buildx build --file ./Dockerfile.prod --tag ghcr.io/dvk-devops/dvk-project:latest --platform linux/amd64,linux/arm64 --push .
