name: Golangci Lint
on:
  pull_request:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  checks: write


jobs:
  golangci-lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest
          working-directory: go
          #only-new-issues: true