name: Scheduled Health Check

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:
  push: 
    branches: [healthcheck]

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check health endpoint
        id: health-check
        run: |
          echo "Testing health check on branch: ${{ github.ref_name }}"
          curl -f --max-time 30 http://${{ secrets.VM_HOST }}:8080/api/health || (echo "App health check failed!" && exit 1)
